"""temperd constants."""

APP_NAME = "temperd"
VERSION = "0.1.1"

## Argument defaults
DEF_POLL_INTERVAL = 60
DEF_REFRESH_INTERVAL = 600
DEF_CHANGE_THRESHOLD = 1.0
DEF_UNAVAILABLE_PAYLOAD = "OFFLINE"
MIN_POLL_INTERVAL = 5
